package org.conversor;

import java.util.List;

public class Listas {
    public List<String> listaMonedas() {
        return List.of("     ---------",
                "AED Dirham de los Emiratos Árabes Unidos",
                "AFN Afgani afgano",
                "ALL Lek albanés",
                "AMD Dram armenio",
                "ANG Florín antillano neerlandés",
                "AOA Kwanza angoleño",
                "ARS Peso argentino",
                "AUD Dólar australiano",
                "AWG Florín arubeño",
                "AZM Manat azerbaiyano",
                "BAM Marco convertible de Bosnia-Herzegovina",
                "BBD Dólar de Barbados",
                "BDT Taka de Bangladesh",
                "BGN Lev búlgaro",
                "BHD Dinar bahreiní",
                "BIF Franco burundés",
                "BMD Dólar de Bermuda",
                "BND Dólar de Brunéi",
                "BOB Boliviano de Bolivia",
                "BRL Real brasileño",
                "BSD Dólar bahameño",
                "BTN Ngultrum de Bután",
                "BWP Pula de Botsuana",
                "BYR Rublo bielorruso",
                "BZD Dólar de Belice",
                "CAD Dólar canadiense",
                "CDF Franco congoleño",
                "CHF Franco suizo",
                "CLP Peso chileno",
                "CNY Yuan Renminbi de China",
                "COP Peso colombiano",
                "CRC Colón costarricense",
                "RSD Dinar serbio ",
                "CUP Peso cubano",
                "CUC Peso cubano convertible",
                "CVE Escudo caboverdiano",
                "CYP Libra chipriota",
                "CZK Koruna checa",
                "DJF Franco yibutiano",
                "DKK Corona danesa",
                "DOP Peso dominicano",
                "DZD Dinar algerino",
                "EEK Corona estonia",
                "EGP Libra egipcia",
                "ERN Nakfa eritreo",
                "ETB Birr etíope",
                "EUR Euro",
                "FJD Dólar fijiano",
                "FKP Libra malvinense",
                "GBP Libra esterlina (libra de Gran Bretaña)",
                "GEL Lari georgiano",
                "GHS Cedi ghanés",
                "GIP Libra de Gibraltar",
                "GMD Dalasi gambiano",
                "GNF Franco guineano",
                "GTQ Quetzal guatemalteco",
                "GYD Dólar guyanés",
                "HKD Dólar de Hong Kong",
                "HNL Lempira hondureño",
                "HRK Kuna croata",
                "HTG Gourde haitiano",
                "HUF Forint húngaro",
                "IDR Rupiah indonesia",
                "ILS Nuevo shéquel israelí",
                "INR Rupia india",
                "IQD Dinar iraquí",
                "IRR Rial iraní",
                "ISK Króna islandesa",
                "JMD Dólar jamaicano",
                "JOD Dinar jordano",
                "JPY Yen japonés",
                "KES Chelín keniata",
                "KGS Som kirguís (de Kirguistán)",
                "KHR Riel camboyano",
                "KMF Franco comoriano (de Comoras)",
                "KPW Won norcoreano",
                "KRW Won surcoreano",
                "KWD Dinar kuwaití",
                "KYD Dólar caimano (de Islas Caimán)",
                "KZT Tenge kazajo",
                "LAK Kip lao",
                "LBP Libra libanesa",
                "LKR Rupia de Sri Lanka",
                "LRD Dólar liberiano",
                "LSL Loti lesotense",
                "LTL Litas lituano",
                "LVL Lat letón",
                "LYD Dinar libio",
                "MAD Dirham marroquí",
                "MDL Leu moldavo",
                "MGA Ariary malgache",
                "MKD Denar macedonio",
                "MMK Kyat birmano",
                "MNT Tughrik mongol",
                "MOP Pataca de Macao",
                "MRO Ouguiya mauritana",
                "MTL Lira maltesa",
                "MUR Rupia mauricia",
                "MVR Rufiyaa maldiva",
                "MWK Kwacha malauiano",
                "MXN Peso mexicano",
                "MYR Ringgit malayo",
                "MZN Metical mozambiqueño",
                "NAD Dólar namibio",
                "NGN Naira nigeriana",
                "NIO Córdoba nicaragüense",
                "NOK Corona noruega",
                "NPR Rupia nepalesa",
                "NZD Dólar neozelandés",
                "OMR Rial omaní",
                "PAB Balboa panameña",
                "PEN Nuevo sol peruano",
                "PGK Kina de Papúa Nueva Guinea",
                "PHP Peso filipino",
                "PKR Rupia pakistaní",
                "PLN zloty polaco",
                "PYG Guaraní paraguayo",
                "QAR Rial qatarí",
                "RON Leu rumano",
                "RUB Rublo ruso",
                "RWF Franco ruandés",
                "SAR Riyal saudí",
                "SBD Dólar de las Islas Salomón",
                "SCR Rupia de Seychelles",
                "SDG Dinar sudanés",
                "SEK Corona sueca",
                "SGD Dólar de Singapur",
                "SHP Libra de Santa Helena",
                "SKK Corona eslovaca",
                "SLL Leone de Sierra Leona",
                "SOS Chelín somalí",
                "SRD Dólar surinamés",
                "STD Dobra de Santo Tomé y Príncipe",
                "SYP Libra siria",
                "SZL Lilangeni suazi",
                "THB Baht tailandés",
                "TJS Somoni tayik (de Tayikistán)",
                "TMT Manat turcomano turcomano",
                "TND Dinar tunecino",
                "TOP Pa'anga tongano",
                "TRY Lira turca",
                "TTD Dólar de Trinidad y Tobago",
                "TWD Dólar taiwanés",
                "TZS Chelín tanzano",
                "UAH Grivna ucraniana",
                "UGX Chelín ugandés",
                "USD Dólar estadounidense",
                "UYU Peso uruguayo",
                "UZS Som uzbeko",
                "VEF Bolívar fuerte venezolano",
                "VND Dong vietnamita",
                "VUV Vatu vanuatense",
                "WST Tala samoana",
                "XAF Franco CFA de África Central",
                "XCD Dólar del Caribe Oriental",
                "XDR Derecho Especial de Giro (DEG  -  FMI)",
                "XOF Franco CFA de África Occidental",
                "YER Rial yemení (de Yemen)",
                "ZAR Rand sudafricano",
                "ZMK Kwacha zambiano",
                "ZWL Dólar zimbabuense");
    }
    public List<String> listaTemperaturas() {
        return List.of("     ---------",
                "C Grados Centigrados o Celsius ",
                "F Grados Farenheit",
                "K Grados Kelvin");
    }
}
